### ISSUE TITLE
Sensor return defaults values at first read, and submodule problem

### ISSUE THREAD

**Issue by TheLongRunSmoke** [sciosense/ens16x-arduino#1]
Hi. I have issue with sensor readings after MCU wakeup, on ESP platform. ESP32 resumes not from a point where sleep command was called, as AVR, but like it is been reset, so when I call ens160.begin() after wakeup, it's call ENS16x::reset() and obviously sensor return defaults on next read.

How to reproduce:
1) Take your [example](https://github.com/sciosense/ens16x-arduino/blob/main/examples/01_Basic/ENS160/ENS160.ino).
2) Add next lines to end of loop() function.
```cpp
// Setup wakeup by a timer.
esp_sleep_enable_timer_wakeup(<time to sleep in ms>  * uS_TO_S_FACTOR);
// Put in to sleep.
esp_deep_sleep_start();
```
3) Compile and upload on any ESP32 MCU.

By design, begin() can't be skipped entirely, but it's be a nice if something like this be part of the library.
```cpp
ens160.begin(&i2c, <reset_skip =>esp_sleep_get_wakeup_cause() == ESP_SLEEP_WAKEUP_TIMER);
```
Well, at least, this is what I did.

---
Another problem. When library used as git submodule Arduino IDE can't find *.inl files. It's not the end of the world, but thing to consider.

**Comment by TheLongRunSmoke** [comment]
read() method use ioInterface field, and it is private. You just can't read anything withou calling ens160.begin(). Sure, it can be done directly, but why this is not part of the library.

**Comment by hal-patryk** [comment]
By making ioInterface private and requiring it to be set via ENS16X::begin(), the ENS16X class enforces a dependency management pattern. This means that any functionality within ENS16X that relies on ioInterface will only work if it has been properly initialized through ENS16X::begin(). This can help in ensuring that ENS16X operates correctly and predictably.
 
As for why this setup not directly included in the library, we made a design decision to provide flexibility and customization options to users. By requiring the initialization of ioInterface through ENS16X::begin(), users have the freedom to choose the specific IoInterface implementation they want to use with ENS16X, allowing for greater versatility and compatibility with different hardware or software environments.

**Comment by TheLongRunSmoke** [comment]
Sure. From an architectural point of view everything is ok. However, this implies that an instance of the ENS16X class is persisted during MCU sleep, not all platforms allow this. What to do, when MCU wakeup, sensor already working, but driver class unitialized?

**Comment by hal-patryk** [comment]
We understand what you are trying to convey, but we cannot provide library to a specific MCU. We will work on improving the library by taking your inputs into consideration. 

And in your case, you can use ESP32 RTC Memory, since the RTC memory doesn’t reset after every wake-up from Deep-sleep.

**Comment by SamFlutterlab** [comment]
Hi, just came across this since I'm encountering a similar scenario but different issue. I used the ESP32 RTC memory to use a bool variable, so that ens161.begin() only runs the first time the device boots up. The code can be found below:
`#include <Arduino.h>
#include <Wire.h>
#include <ScioSense_ENS16x.h>

#include "ens16x_i2c_interface.h"

using namespace ScioSense;

#define I2C_ADDRESS 0x52
I2cInterface i2c;

ENS161 ens161;

RTC_DATA_ATTR bool setupOnce = false;

void setup()
{
    int startTime = millis();
    Serial.begin(115200);
    ens161.enableDebugging(Serial);

    /* Start Wire */
    Wire.begin(21,22);
    i2c.begin(Wire, I2C_ADDRESS);

    /* only run ens161.begin() once */
    while(!setupOnce){
      Serial.println("Init ENS161");
      while (ens161.begin(&i2c) != true)
      {
          Serial.print(".");
          delay(1000);
      }
      Serial.println("success");

      ens161.startLowPowerMeasure();
      setupOnce = true;
    }
    
    /* Measures data */
    Serial.println("Measuring..");
    ens161.wait();

    if (ens161.update() == ENS16x::Result::Ok)
    {
      Serial.println("Result OK");
      if (hasFlag(ens161.getDeviceStatus(), ENS16x::DeviceStatus::NewData))
      {
          Serial.print("AQI UBA:"); Serial.print((uint8_t)ens161.getAirQualityIndex_UBA());

          Serial.print("\tTVOC:"); Serial.print(ens161.getTvoc());
          Serial.print("\tECO2:"); Serial.println(ens161.getEco2());
      }
   
    }
    int endTime = millis();

    /* ESP32 goes to deep sleep */
    esp_sleep_enable_timer_wakeup((120000 - (endTime -startTime)) * 1000);
    Serial.print("Sleeping for: "); Serial.print((120000 - (endTime -startTime))); Serial.println(" milliseconds");
    esp_deep_sleep_start();  
}

void loop()
{
    
}`

However when the ESP32 wakes up again, bypasses ens161.begin() and starts measuring, it doesn't enter the `if(ens161.update() == ENS16x::Result::Ok)` condition. Here's the log I got:

`17:25:04.867 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
17:25:04.867 -> configsip: 0, SPIWP:0xee
17:25:04.867 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
17:25:04.867 -> mode:DIO, clock div:1
17:25:04.894 -> load:0x3fff0030,len:1344
17:25:04.894 -> load:0x40078000,len:13964
17:25:04.894 -> load:0x40080400,len:3600
17:25:04.894 -> entry 0x400805f0
17:25:04.894 -> Init ENS161
17:25:04.894 -> ENS161 debug -- reset status: ok
17:25:04.894 -> ENS161 debug -- PART_ID  :  0x161
17:25:04.894 -> Firmware: 8.0.61
17:25:04.894 -> success
17:25:04.894 -> Measuring..
17:25:06.862 -> Result OK
17:25:06.862 -> AQI UBA:0	TVOC:0	ECO2:0
17:25:08.895 -> Sleeping for: 117976 milliseconds
17:27:05.996 -> ets Jul 29 2019 12:21:46
17:27:05.996 -> 
17:27:05.996 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
17:27:05.996 -> configsip: 0, SPIWP:0xee
17:27:05.996 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
17:27:06.035 -> mode:DIO, clock div:1
17:27:06.035 -> load:0x3fff0030,len:1344
17:27:06.035 -> load:0x40078000,len:13964
17:27:06.035 -> load:0x40080400,len:3600
17:27:06.035 -> entry 0x400805f0
17:27:06.035 -> Measuring..
17:27:09.049 -> Sleeping for: 119000 milliseconds
17:29:07.532 -> ets Jul 29 2019 12:21:46
17:29:07.532 -> 
17:29:07.532 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
17:29:07.532 -> configsip: 0, SPIWP:0xee
17:29:07.532 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
17:29:07.532 -> mode:DIO, clock div:1
17:29:07.532 -> load:0x3fff0030,len:1344
17:29:07.532 -> load:0x40078000,len:13964
17:29:07.532 -> load:0x40080400,len:3600
17:29:07.532 -> entry 0x400805f0
17:29:07.629 -> Measuring..
17:29:10.599 -> Sleeping for: 119000 milliseconds
`

If I replace the ESP32 deep sleep operation to just a simple delay, then I'm able to read the data from the ENS161. By right the ENS161 should continue running regardless of the ESP32 going to sleep or not, but I'm not sure why I'm not getting the data I need.

**Comment by TRScioSense** [comment]
Unfortunately this issue is related to the MCU and how DeepSleep is handled; as a consequence, the ESP32 has to reinitialize the driver instance which causes a restart of ENS160
